server:
  port:  9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_db?useSSL=false
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialization-mode: always
  jpa:
    database: mysql
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
